spring.application.name=b5-jpa


spring.datasource.url=jdbc:mysql://localhost:3306/b5jpa?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=oooooooo

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true