spring.application.name=demo-b5-first-project

#spring defined properties
server.port=9090

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

#mysql.username=


#user defined dependency
library.no.of.books=10
#library.no.of.books_staging=10
#library.no.of.books_prod=10


spring.profiles.active=staging,uat,prod

logging.level.org.springframework.boot=info

logging.level.org.apache.catalina=error

#logging.level.root=error
logging.level.com.example.demo_b5_first_project=error