spring.application.name=B5Oauth


spring.security.oauth2.client.registration.google.client-id=992320458261-69lh0tu74rh0m68o773p8a54le28kmac.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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



spring.security.oauth2.client.registration.github.client-id=Ov23liZrVNxKrabsmz4F
spring.security.oauth2.client.registration.github.client-secret=b3bffa5dd0d9e7f49580b52d8f19a570235edc2d