spring.application.name=b5MinorProject1


spring.datasource.url=jdbc:mysql://localhost:3306/b5MinorProject2?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=oooooooo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


library.student.bookLimit=3
library.day.limit=15
fine.per.day=10